name: Keep Streamlit App Alive

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        # This simple curl command wakes up the app / prevents it from sleeping
        run: curl -sL https://doorway-checker.streamlit.app/ > /dev/null
